version: "3.8"

services:
  postgres:
    image: postgres
    container_name: ppwii-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ppwii_db
      POSTGRES_USER: ppwii_user
      POSTGRES_PASSWORD: ppwii_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
